# Generated by Django 3.2.5 on 2021-12-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=40)),
                ('train_no', models.CharField(max_length=6)),
                ('train_starting', models.CharField(max_length=20)),
                ('train_ending', models.CharField(max_length=20)),
                ('timing', models.TimeField()),
            ],
        ),
    ]
