# Generated by Django 3.2.5 on 2021-12-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irctc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='timing',
            field=models.DateTimeField(),
        ),
    ]
