# Generated by Django 3.2.5 on 2021-12-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irctc', '0002_alter_train_timing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_starting', models.CharField(max_length=20)),
                ('train_ending', models.CharField(max_length=20)),
                ('timing', models.DateTimeField()),
            ],
        ),
    ]
